
server:
  port: 8080

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
endpoints:
  shutdown:
    enabled: true

spring:
  messages:
    basename: i18n/messages

mqtt:
  broker:
    host: localhost
    port: 1883
